export const actividadDocenteJson = {
    dependencia: [
        "Decanatura de Ingeniería",
        "Decanatura de Ciencias Económicas",
        "Decanatura de Ciencias Jurídicas",
        "Decanatura de Ciencias de la Salud",
        "Decanatura de Educación",
        "Administrativa Central"
    ],
    carrera: [
        "Ingeniería Civil",
        "Ingeniería Electrónica",
        "Ingeniería Industrial",
        "Ingeniería de Sistemas",
        "Ingeniería Mecánica",
        "Ingeniería de Minas",
        "Administración de Empresas",
        "Contaduría Pública",
        "Derecho",
        "Medicina",
        "Enfermería",
        "Odontología",
        "Psicología",
        "Educación Inicial",
        "Educación Primaria",
        "Educación Secundaria",
        "Trabajo Social",
        "Comunicación Social",
        "Ciencias de la Computación"
    ],
    materia: [
        "Matemática I",
        "Matemática II",
        "Física I",
        "Física II",
        "Química General",
        "Programación I",
        "Programación II",
        "Algoritmos y Estructuras de Datos",
        "Contabilidad General",
        "Derecho Constitucional",
        "Derecho Penal",
        "Anatomía",
        "Fisiología",
        "Psicología General",
        "Pedagogía General",
        "Didáctica",
        "Metodología de la Investigación",
        "Ética Profesional",
        "Administración de Recursos Humanos"
    ],
    categoria: [
        "Titular",
        "Asociado",
        "Auxiliar",
        "Instructor",
        "Docente Permanente",
        "Docente Contratado"
    ],
    cargo: [
        "Profesor Titular",
        "Profesor Asociado",
        "Profesor Auxiliar",
        "Instructor",
        "Coordinador de Carrera",
        "Jefe de Área",
        "Director de Instituto",
        "Administrador",
        "Asistente Administrativo",
        "Secretario Académico"
    ],
    cargaHoraria: ["16", "32", "48", "64", "80", "96", "112", "128", "144", "160"],
    dias: ["Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado"]
};
